services:
  postgres:
    image: postgres:16
    container_name: jobtracker-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jobtracker-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobtracker-backend
    env_file:
      .env
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      # if your backend connects to postgres inside docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_PROFILES_ACTIVE: local,dev

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - jobtracker-network

volumes:
  postgres_data:

networks:
  jobtracker-network:
    driver: bridge
